image:
  file: .gitpod.dockerfile
tasks:
  - command: >
      cd app &&
      npm install &&
      dotnet watch run app.csproj --urls http://127.0.0.1:8000 &&
      npm run build
ports:
  - port: 8000